<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSbot3 robot.

  Author: Helio Perroni Filho
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros_commons)/urdf/domain.xacro"/>
  <xacro:property name="M" value="0.001"/>
  
  <!-- Overall height of the robot body without camera and LiDAR -->
  <xacro:property name="overall_height" value="${103.0 * M}"/>

  <!-- Total height including the camera support -->
  <xacro:property name="overall_height_with_camera_support" value="${197.0 * M}"/>

  <!-- Height the chassis is above the ground -->
  <xacro:property name="ground_clearance" value="${23.0 * M}"/>

  <!-- Using standard wheels -->
  <xacro:property name="wheel_diameter" value="${84.0 * M}"/>
  <xacro:property name="wheel_wheelbase" value="${106.0 * M}"/>

  <!-- Wheel width is not provided in the manual https://husarion.com/manuals/rosbot -->
  <!-- Picking a random but reasonable value -->
  <xacro:property name="wheel_width" value="${30.0 * M}"/> <!-- Not provided in the manual -->

  <!-- Dimensions of the robot main body -->
  <xacro:property name="chassis_length" value="${200.0 * M}"/>
  <xacro:property name="chassis_width" value="${233.0 * M}"/>
  <xacro:property name="chassis_height" value="${overall_height - ground_clearance}"/>

  <!-- Camera position relative to the payload base -->
  <xacro:property name="camera_displacement_x" value="${0.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_displacement_z" value="${overall_height_with_camera_support - overall_height}"/>

  <!-- Camera support -->
  <xacro:property name="camera_support_width" value="${10.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_support_depth" value="${30.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_support_angle" value="${60.0 * DEG}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_support_displacement_x" value="${-camera_displacement_z / tan(camera_support_angle - camera_displacement_x)}"/> <!-- Not provided in the manual -->

  <!-- Dimensions of the camera itself -->
  <xacro:property name="camera_height" value="${30.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_width" value="${80.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_depth" value="${15.0 * M}"/> <!-- Not provided in the manual -->

  <!-- Dimensions of the LiDAR itself -->
  <xacro:property name="lidar_side" value="${45.61 * M}"/>
  <xacro:property name="lidar_height" value="${37.6 * M}"/>

  <link name="base_link"/>
  <xacro:joint_fixed
    parent="base_link"
    child="chassis"
    z="${ground_clearance + 0.5 * body_height}"
  />

  <xacro:solid_block
    name="chassis"
    size_x="${chassis_length}"
    size_y="${chassis_width}"
    size_z="${chassis_height}"
  />

  <xacro:joint_fixed
    parent="chassis"
    child="payload_base"
    z="${0.5 * body_height}"
  />

  <xacro:solid_block
    name="camera_support"
    size_x="${camera_support_depth}"
    size_y="${camera_support_width}"
    size_z="${camera_support_height / cos(camera_support_angle)}"
    pitch="${camera_support_angle}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="camera_support"
    x="${0.5 * payload_base_length}"
    z="${0.5 * (payload_base_height + camera_support_height / cos(camera_support_angle))}"
  />

  <xacro:camera_link name="camera_front"/>
  <xacro:joint_fixed
    parent="payload_base"
    child="camera_front"
    z="${camera_support_height - camera_height * 0.5 }"
  />

  <xacro:solid_block
    name="lidar"
    size_x="${lidar_side}"
    size_y="${lidar_side}"
    size_z="${lidar_height}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="lidar"
    x="${0.5 * payload_base_height}"
    z="${0.5 * (payload_base_height + lidar_height)}"
  />

  <link name="laser"/>
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />
</robot>
