<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSbot3 robot.

  Author: Helio Perroni Filho
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros_commons)/urdf/domain.xacro"/>
  <xacro:property name="M" value="0.001"/>
  
  <!-- Overall height of the robot body without camera and LiDAR -->
  <xacro:property name="overall_height" value="${103.0 * M}"/>

  <!-- Total height including the camera support -->
  <xacro:property name="overall_height_with_camera_support" value="${197.0 * M}"/>

  <!-- Total height including the LiDAR -->
  <xacro:property name="overall_height_with_lidar" value="${141.0 * M}"/>

  <!-- Height the chassis is above the ground -->
  <xacro:property name="ground_clearance" value="${23.0 * M}"/>

  <!-- Using standard wheels -->
  <xacro:property name="wheel_diameter" value="${84.0 * M}"/>
  <xacro:property name="wheel_wheelbase" value="${106.0 * M}"/>

  <!-- Wheel width is not provided in the manual https://husarion.com/manuals/rosbot -->
  <!-- Picking a random but reasonable value -->
  <xacro:property name="wheel_width" value="${30.0 * M}"/> <!-- Not provided in the manual -->

  <!-- Dimensions of the robot main body -->
  <xacro:property name="chassis_length" value="${200.0 * M}"/>
  <xacro:property name="chassis_width" value="${233.0 * M}"/>
  <xacro:property name="chassis_height" value="${overall_height - ground_clearance}"/>

  <!-- Dimensions of the camera itself -->
  <xacro:property name="camera_height" value="${30.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_width" value="${80.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_depth" value="${15.0 * M}"/> <!-- Not provided in the manual -->

  <!-- Camera position relative to the payload base -->
  <xacro:property name="camera_displacement_x" value="${0.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="camera_displacement_z" value="${overall_height_with_camera_support - overall_height - camera_height * 0.5 }"/>

  <!-- Dimensions of the LiDAR itself -->
  <xacro:property name="lidar_diameter" value="${80.0 * M}"/>
  <xacro:property name="lidar_height" value="${overall_height_with_lidar - overall_height_with_camera_support}"/>

  <!-- LiDAR position relative to the payload base -->
  <xacro:property name="lidar_displacement_x" value="${0.0 * M}"/> <!-- Not provided in the manual -->
  <xacro:property name="lidar_displacement_z" value="${overall_height_with_lidar - overall_height - lidar_height * 0.5 }"/>

  <link name="base_link"/>
  <xacro:joint_fixed
    parent="base_link"
    child="chassis"
    z="${ground_clearance + 0.5 * body_height}"
  />

  <xacro:solid_block
    name="chassis"
    size_x="${chassis_length}"
    size_y="${chassis_width}"
    size_z="${chassis_height}"
  />

  <xacro:joint_fixed
    parent="chassis"
    child="payload_base"
    z="${0.5 * body_height}"
  />

  <xacro:solid_block
    name="camera_support"
    size_x="${camera_width}"
    size_y="${camera_depth}"
    size_z="${camera_height}"
  />

  <xacro:camera_link name="camera_front"/>
  <xacro:joint_fixed
    parent="payload_base"
    child="camera_front"
    x="${camera_displacement_x}"
    z="${camera_displacement_z}"
  />

  <xacro:solid_cylinder
    name="lidar"
    radius="${lidar_diameter * 0.5}"
    length="${lidar_height}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="lidar"
    x="${lidar_displacement_x}"
    z="${lidar_displacement_z}"
  />

  <link name="laser"/>
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />
</robot>
